name: Docker

on:
  push:
    tags: 
      - 'v*'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
          
      - 
        name: Docker meta Website
        id: docker_meta-website
        uses: crazy-max/ghaction-docker-meta@v1
        with:
          images: ghcr.io/jamaki5/website
          
      -
        name: Build and push website
        uses: docker/build-push-action@v2
        with:
          context: ./client
          platforms: linux/amd64
          push: true
          tags: ${{ steps.docker_meta-website.outputs.tags }}
          labels: ${{ steps.docker_meta-website.outputs.labels }}
